### ISSUE TITLE
Remove favorites from the profile page

### ISSUE THREAD

**Issue by Cactooz** [Cactooz/StarWarsWiki#47]
Currently, you need to click on an item and go to its page to remove it from the favorites list.
It would be better UX to have a remove favorite button in the favorites list in the profile view.

**Comment by pilsnerfrajz** [comment]
Worked this way until [#45](https://github.com/Cactooz/StarWarsWiki/pull/45)

**Comment by pontaberglund** [comment]
Fixed now in #49, sorry for the inconvenience.
