### ISSUE TITLE
Remove n/a and none from more results

### ISSUE THREAD

**Issue by Cactooz** [Cactooz/StarWarsWiki#59]
Some characters like Darth Vader and Jabba the Hutt have more details with the values as `n/a` or `none`. These should also be filtered out just like `unknown`.

**Comment by Cactooz** [comment]
For planets, the climate and terrain get removed because they are arrays. They should be kept and joined with commas.

**Comment by pilsnerfrajz** [comment]
Pages like `C-3PO` and `Dagobah` have capital `N/A` in the more details view. This needs to be filtered as well.

**Comment by pilsnerfrajz** [comment]
Fixed by #67
