### ISSUE TITLE
Details view images don't behave as specified in stylesheet

### ISSUE THREAD

**Issue by pilsnerfrajz** [Cactooz/StarWarsWiki#65]
## Bug
On branch `styling`, the images, in the details view, are not the correct size. This only seems to be an issue with Firefox. The Firefox version is 120.0.1. and all extensions are disabled.

### Chrome (correct)
<img width="1439" alt="chrome" src="https://github.com/Cactooz/StarWarsWiki/assets/94441813/bfdd8a29-f67a-4ccc-acb0-7005c3349900">

### Firefox (incorrect)
<img width="1440" alt="firefox" src="https://github.com/Cactooz/StarWarsWiki/assets/94441813/1dc8b7fd-98c3-420e-b0e8-cf668f3fd6c4">

**Comment by pilsnerfrajz** [comment]
Potential fix. Removing [line 186](https://github.com/Cactooz/StarWarsWiki/blob/46dae8921717c8ff4465043d0f84d1d3ebab5b41/starwarswiki/src/style/style.scss#L186C4-L186C4) seems to fix the problem. At least it looks the same in both Chrome and Firefox after removing it.

**Comment by Cactooz** [comment]
> Potential fix. Removing [line 186](https://github.com/Cactooz/StarWarsWiki/blob/46dae8921717c8ff4465043d0f84d1d3ebab5b41/starwarswiki/src/style/style.scss#L186C4-L186C4) seems to fix the problem. At least it looks the same in both Chrome and Firefox after removing it.

Yup good catch, that should be it!

**Comment by pilsnerfrajz** [comment]
Also, line 187 seems redundant.

**Comment by Cactooz** [comment]
> Also, line 187 seems redundant.

That line is there in order for tall images like 4-LOM to not get extremely big on mobile.

**Comment by Cactooz** [comment]
> > Potential fix. Removing [line 186](https://github.com/Cactooz/StarWarsWiki/blob/46dae8921717c8ff4465043d0f84d1d3ebab5b41/starwarswiki/src/style/style.scss#L186C4-L186C4) seems to fix the problem. At least it looks the same in both Chrome and Firefox after removing it.
> 
> Yup good catch, that should be it!

This is also not it. Both 186 and 187 is for mobile, not desktop. Both of them are needed. It's something in the media query that might be wrong instead.

**Comment by Cactooz** [comment]
Solved with #70
