### ISSUE TITLE
URL breaks because of animations

### ISSUE THREAD

**Issue by pilsnerfrajz** [Cactooz/StarWarsWiki#76]
### Bug
When clicking a card, the animation is so slow that you can click the card multiple times, making the URL concatenate the path several times. 

### To reproduce
1. Go to characters in the browse view
2. Click `"Hyper" Rod` many times before the page is changed. The URL will change to `/characters/"Hyper" Rod/"Hyper" Rod`, breaking the page.

**Comment by pontaberglund** [comment]
Fixed in #88
