### ISSUE TITLE
Landing card text overflows

### ISSUE THREAD

**Issue by pilsnerfrajz** [Cactooz/StarWarsWiki#95]
Landing card text exceed the borders of the cards on the landing page on small screens.

<img width="363" alt="Skärmavbild 2023-12-20 kl  18 22 18" src="https://github.com/Cactooz/StarWarsWiki/assets/94441813/cfaf41d9-0fe2-4d49-a6ca-faa609584cbb">

This is not a problem in browse.

<img width="362" alt="Skärmavbild 2023-12-20 kl  18 23 41" src="https://github.com/Cactooz/StarWarsWiki/assets/94441813/29181710-58bd-4902-b492-92968fa2ab2d">

**Comment by Cactooz** [comment]
Solved with #97
