### ISSUE TITLE
Search result stays but you can't search again

### ISSUE THREAD

**Issue by Cactooz** [Cactooz/StarWarsWiki#98]
After you have search for something like "Mustafar" and you click to go to that page. The Mustafar search text then stays in the search bar, but if you focus on the search again and press enter then you get No results. 

Would probably be good to clear the search bar after a search has been done.

**Comment by Cactooz** [comment]
Also going directly to the link `/search/Mustafar` or even just `/search/` gives No results.

**Comment by pontaberglund** [comment]
Fixed in #114
